config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  
  resources :lists, except: :show, shallow: true do
    resources :tasks, except: [:show, :index] do
      member do
        patch 'set_completed'
      end
    end
  end

  root 'welcome#index'

end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :user
  has_many :tasks, dependent: :destroy
  
  validates :title, presence: true, length: { minimum: 4 }

  def completed?
    status = true
    tasks.each do |task|
      if task.uncompleted?
        status = false
      end
    end
    status
  end

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :list
  
  validates :content, presence: true, length: { minimum:6 }
  validates :content, uniqueness: {message: "has already been used"}

  def uncompleted?
    !completed
  end

  # Extract options_for_select array from the view just for clarity
  def self.priority_options
    [['Very high', 1], ['High', 2], ['Normal', 3],['Low', 4]]
  end

  def print_priority
    case priority
      when 1
        "Very high"
      when 2
        "High"
      when 3
        "Normal"
      when 4
        "Low"
      else
        "Not specified"
      end
  end

  def print_deadline
    deadline ? deadline.strftime("Complete before %d/%m/%Y %n | %H:%M") : "None"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :lists

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :email_regexp =>  /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource_or_scope)
    stored_location_for(resource_or_scope) ||
    if store_location_for(:list, lists_path)
      lists_path
    else
      super
    end
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @lists = current_user.lists
  end

  def new
    @list = current_user.lists.build
  end

  def edit
    if @list.user_id != current_user.id
      flash[:alert] = "Nice try, but you can't edit list, which doesn't belongs to you"
      redirect_to lists_path
    end
  end

  def create
    @list = current_user.lists.build(list_params)
    if @list.save
      flash[:notice] = "List was successfully created."
      redirect_to lists_path
    else
      flash.now[:alert] = "Something wrong with you data. Try again"
      render :new
    end
  end

  def update
    if @list.update_attributes(list_params)
      flash[:notice] = "List was successfully updated."
      redirect_to lists_path
    else
      flash.now[:alert] = "Something wrong with you data. Try again"
      render :new
    end
  end

  def destroy
    if @list.completed?
      @list.destroy
      flash[:notice] = "List was successfully destroyed."
    else
      flash[:alert] = "List can not be removed because contains uncompleted tasks"
    end
    redirect_to lists_path
  end

  private

    def set_list
      @list = List.find(params[:id])
    end

    def list_params
      params.require(:list).permit(:title)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_related_list, only: [:new, :create]
  before_action :set_task, only: [:edit, :update, :destroy, :set_completed]
  before_action :authenticate_user!

  def new
    if @related_list.user_id != current_user.id
      flash[:alert] = "Nice try, but you can't add task to the list, that doesn't belongs to you"
      redirect_to lists_path
    else
      @task = @related_list.tasks.build
    end
  end

  def create
    @task = @related_list.tasks.build(task_params)
    if @task.save
      flash[:notice] = "Task was successfully created"
      redirect_to lists_path
    else
      flash.now[:alert] = "Something wrong with you data. Try again"
      render :new
    end
  end

  def edit
    # Check task for completion just for reliability. Though we hide edit link
    # when task has been completed, user can type the request manually. Also check if
    # this task belongs to the user's list.
    if @task.list.user_id != current_user.id
      flash[:alert] = "Nice try, but you can't edit task, that doesn't belongs to your list"
      redirect_to lists_path
    elsif @task.completed?
      flash[:alert] = "Sorry, pal, but you can't edit completed task"
      redirect_to lists_path
    end
  end

  def update
    if @task.update_attributes(task_params)
      flash[:notice] = "Task was successfully updated"
      redirect_to lists_path
    else
      flash.now[:alert] = "Something wrong with you data. Try again"
      render :new
    end
  end

  def destroy
    if @task.completed?
      flash[:alert] = "Sorry, but you can't delete completed task"
    else
      @task.destroy
      flash[:notice] = "Task was successfully deleted"
    end
    redirect_to lists_path
  end

  def set_completed
    if @task.completed?
      flash[:alert] = "Sorry, this task has been completed before"
    else
      @task.update_attribute(:completed, true)
      flash[:notice] = "Task was completed. Great job!"
    end
    redirect_to lists_path
  end

  private

    def set_related_list
      @related_list = List.find(params[:list_id])
    end

    def set_task
      @task = Task.find(params[:id])
    end

    def task_params
      params.require(:task).permit(:content, :deadline, :priority, :list_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    if user_signed_in?
      redirect_to lists_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Roboto:300,900' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<%= render 'shared/navbar' %>

<% flash.each do |type, message| %>
  <%= content_tag(:div, message, class: "alert alert-#{type}") %>
<% end %>

<%= yield %>

</body>
</html>

app/views/lists/_form.html.erb
<%= form_for @list, validate: true do |f| %>
  <% if @list.errors.any? %>
    <%= render partial: "shared/errors", locals: {object: @list} %>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control", placeholder: "Enter title of the todo list", autofocus: true %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary"%>
  </div>
<% end %>

app/views/lists/_list_header.html.erb
<tr class="list_header">
  <th class="list_title" colspan="4" width = "80%">
    <%= fa_icon "calendar"%>
    <h2 style="display:inline"><%= list.title %></h2>
  </th>

  <th class="list_actions" width = "20%">
    <%= link_to new_list_task_path(list), title: "Add new task" do %>
    <%= fa_icon "plus"%>
    <% end %>

    <%= link_to edit_list_path(list), title: "Edit todo list" do %>
      <%= fa_icon "pencil" %>
    <% end %>

    <%= link_to list_path(list), title: "Delete todo list", method: :delete, data: {confirm: "Are you sure?"} do %>
      <%= fa_icon "trash" %>
    <% end %>
  </th>
</tr>
<% if list.tasks.any?  %>
  <tr class="task_header">
    <th></th>
    <th> Content </th>
    <th> Deadline </th>
    <th> Priority </th>
    <th colspan="3"></th>
  </tr>
<% end %>

app/views/lists/edit.html.erb
<%= content_for :title, "Task Manager | Editing '#{@list.title}' list" %>
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1 class="text-center form-header"><%= "Editing '#{@list.title}' list" %></h1>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/lists/index.html.erb
<%= content_for :title, "Task Manager | #{current_user.email} todo lists" %>
<div class="container">
  <% if @lists.count > 0 %>
    <div id="todo_lists">
      <h2 class="text-center second-header"> My TODO lists</h2>
      <% @lists.each do |list| %>
        <table id = "<%= dom_id(list) %>" class="table">
          <thead>
            <%= render partial: "list_header", locals: {list: list} %>
          </thead>
          <tbody class="task_list">
              <%= render partial: "tasks/task_list", locals: {list: list}%>
          </tbody>
        </table>
      <% end %>
    </div>
  <% else %>
    <h2 class="text-center second-header"> You don't have any lists yet</h2>
  <% end %>

  <%= button_to new_list_path, method: :get, class: "btn btn-primary btn-lg" do %>
    <%= fa_icon "plus", text: "Add new TODO list" %>
  <% end %>
</div>

app/views/lists/new.html.erb
<%= content_for :title, "Task Manager | Add new todo list" %>
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1 class="text-center form-header">New List</h1>
      <%= render 'form' %>
    </div>
  <div>
</div>

app/views/shared/_errors.html.erb
<div id="error_explanation">
  <h4><%= pluralize(object.errors.count, "error") %> prohibited this list from being saved:</h4>
  <ul>
  <% object.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
      <%= link_to "Task Manager", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Signed as <%= current_user.email %><b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "My TODO lists", lists_path %></li>
              <li><%= link_to "Edit my profile", edit_user_registration_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Log out", destroy_user_session_path, method: :delete%></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", new_user_session_path %></li>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/tasks/_form.html.erb
<%= form_for [@related_list, @task], validate: true do |f| %>
<% if @task.errors.any? %>
  <%= render partial: "shared/errors", locals: {object: @task} %>
<% end %>

  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_field :content, autofocus: true, class: "form-control", placeholder: "Enter task content" %>
  </div>

  <div class="form-group">
    <%= f.label :deadline, "Set up deadline (not necessary)" %>
    <%= f.datetime_local_field :deadline, class: "form-control"%>
  </div>

  <div class="form-group">
    <%= f.label :priority, "Select priority for your task" %> 
    <%= f.select :priority, options_for_select(Task.priority_options, @task.priority), {prompt: nil}, class: "form-control"%>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-primary"%>
  </div>

<% end %>

app/views/tasks/_task_list.html.erb
<% list.tasks.order(completed: :desc, priority: :asc).each do |task| %>
  <tr id= "<%= dom_id(task) %>" >
    <td width="5%" align="center">
      <% if task.completed? %>
        <%= fa_icon "check-square-o" %>
      <% else %>
        <%= fa_icon "square-o" %>
      <% end %>
    </td>
    <td width="35%"> <%= task.content %> </td>
    <td width="30%"> <%= task.print_deadline %> </td>
    <td width="10%"> <%= task.print_priority %> </td>

    <td class="task_actions" width="20%">
      <% if task.uncompleted? %>
        <%= link_to set_completed_task_path(task), title: "Mark as complete", method: :patch do %>
          <%= fa_icon "bookmark-o" %>
        <% end %>

        <%= link_to edit_task_path(task), title: "Edit this task" do %>
          <%= fa_icon "pencil" %>
        <% end %>

        <%= link_to task_path(task), title: "Delete this task", method: :delete, data: {confirm: "Are you sure?"} do %>
          <%= fa_icon "trash" %>
        <% end %>
      <% end %>
    </td>
  </tr>
<% end %>

app/views/tasks/edit.html.erb
<%= content_for :title, "Task Manager | Editing '#{@task.content}' task" %>
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1 class="text-center form-header"><%= "Editing '#{@task.content}' task" %></h1>
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/tasks/new.html.erb
<%= content_for :title, "Task Manager | Add new task" %>
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1 class="text-center form-header">New task for '<%= @task.list.title%>' list</h1>
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<% content_for :title, "Task Manager" %>
<div class="container">
  <div class="print text-center">
    <h1 class="main-header">TODO list application for Ruby Garage</h1>
    <h2 class="second-header">Control your task flow more efficiently</h2>
  </div>
  <div class="actions">
    <%= button_to "Log in",  new_user_session_path, method: :get, class: "btn btn-default" %>
    <%= button_to "Sign up",  new_user_registration_path, method: :get, class: "btn btn-default" %>
  </div>
</div>